spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/makrosfactory?currentSchema=public
    username: postgres
    password: j1j2j3j4

jwt:
  secret: ${JWT_SECRET}